"""AI configuration and workspace tab construction for the universal UI."""

from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QPlainTextEdit,
    QPushButton,
    QSplitter,
    QSpinBox,
    QTableWidget,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from universal_core import (
    AI_MODEL_USE_CASE_PRESETS,
    AI_PROVIDER_PRESETS,
    DEFAULT_PAGE_LIMIT,
    DEFAULT_SCROLL_TIMES,
    scene_template_presets,
)

def build_ai_tab(self):
    page = QWidget()
    layout = QVBoxLayout(page)
    splitter = QSplitter(Qt.Orientation.Horizontal)

    config_box = QGroupBox("AI 配置中心（仅远程 API）")
    self.ai_config_box = config_box
    config_layout = QGridLayout(config_box)
    self.ai_provider_boundary_label = QLabel(
        "当前为模型 API：用于 AI 建议列、字段修复、自然语言任务和文件识别。"
    )
    self.ai_provider_boundary_label.setWordWrap(True)
    self.api_health_label = QLabel("API 体检：等待配置")
    self.api_health_label.setWordWrap(True)
    self.ai_provider_combo = QComboBox()
    for key, preset in AI_PROVIDER_PRESETS.items():
        self.ai_provider_combo.addItem(preset["name"], key)
    self.ai_provider_combo.currentIndexChanged.connect(self.on_ai_provider_changed)
    self.ai_format_combo = QComboBox()
    for value, text in (
        ("openai_compatible", "OpenAI 兼容"),
        ("anthropic", "Anthropic Claude"),
        ("gemini", "Google Gemini"),
        ("thunderbit_extract", "第三方抽取接口"),
    ):
        self.ai_format_combo.addItem(text, value)
    self.ai_format_combo.currentIndexChanged.connect(self.update_ai_provider_boundary)
    self.ai_base_url_input = QLineEdit()
    self.ai_models_url_input = QLineEdit()
    self.ai_model_search_input = QLineEdit()
    self.ai_model_search_input.setPlaceholderText("搜索模型，例如 gpt / qwen / vision")
    self.ai_model_search_input.textChanged.connect(self.filter_ai_models)
    self.ai_model_combo = QComboBox()
    self.ai_model_combo.setEditable(True)
    self.ai_model_combo.lineEdit().setPlaceholderText("可选择模型，也可直接粘贴厂商文档里的模型名")
    self.ai_model_count_label = QLabel("可选模型：0")
    self.ai_model_hint_label = QLabel("当前模型：等待选择")
    self.ai_model_hint_label.setWordWrap(True)
    self.ai_model_combo.currentTextChanged.connect(self.update_ai_model_hint)
    self.ai_use_case_combo = QComboBox()
    for key, preset in AI_MODEL_USE_CASE_PRESETS.items():
        self.ai_use_case_combo.addItem(preset["name"], key)
    self.ai_auto_apply_use_case_checkbox = QCheckBox("向导自动切换模型")
    self.ai_auto_apply_use_case_checkbox.setChecked(True)
    self.ai_apply_use_case_button = QPushButton("应用用途")
    self.ai_apply_use_case_button.clicked.connect(self.apply_ai_use_case_preset)
    self.ai_key_input = QLineEdit()
    self.ai_key_input.setEchoMode(QLineEdit.EchoMode.Password)
    self.ai_key_input.setPlaceholderText("API Key 只保存在本机配置文件；AI 功能只调用远程 API")
    self.ai_key_name_input = QLineEdit()
    self.ai_key_name_input.setPlaceholderText("Key 名称，例如 主账号 / 备用")
    self.ai_key_combo = QComboBox()
    self.ai_key_combo.currentIndexChanged.connect(self.on_ai_key_selected)
    self.ai_key_show_button = QPushButton("显示")
    self.ai_key_add_button = QPushButton("保存为 Key")
    self.ai_key_delete_button = QPushButton("删除 Key")
    self.ai_key_use_available_button = QPushButton("切换可用 Key")
    self.ai_key_show_button.clicked.connect(self.toggle_ai_key_visibility)
    self.ai_key_add_button.clicked.connect(self.add_or_update_ai_key)
    self.ai_key_delete_button.clicked.connect(self.delete_current_ai_key)
    self.ai_key_use_available_button.clicked.connect(self.switch_to_available_ai_key)
    self.ai_save_button = QPushButton("保存配置")
    self.ai_test_button = QPushButton("测试 API")
    self.ai_diagnose_button = QPushButton("诊断配置")
    self.ai_apply_preset_button = QPushButton("应用推荐配置")
    self.ai_fetch_models_button = QPushButton("拉取模型")
    self.ai_cleanup_user_data_button = QPushButton("清理本机数据")
    self.ai_save_button.clicked.connect(self.save_ai_settings_from_ui)
    self.ai_test_button.clicked.connect(self.test_ai_api)
    self.ai_diagnose_button.clicked.connect(self.diagnose_ai_api)
    self.ai_apply_preset_button.clicked.connect(self.apply_recommended_ai_settings)
    self.ai_fetch_models_button.clicked.connect(self.fetch_ai_models)
    self.ai_cleanup_user_data_button.clicked.connect(self.confirm_cleanup_user_data)
    self.ai_provider_overview_table = QTableWidget(0, 9)
    self.ai_provider_overview_table.setHorizontalHeaderLabels(
        ["当前", "厂商", "配置", "模型数", "当前模型", "Key", "接口", "在线模型", "连接测试"]
    )
    self.ai_provider_overview_table.verticalHeader().setVisible(False)
    self.ai_provider_overview_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
    self.ai_provider_overview_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
    self.ai_provider_overview_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_provider_overview_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_provider_overview_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_provider_overview_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_provider_overview_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_provider_overview_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_provider_overview_table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_provider_overview_table.horizontalHeader().setSectionResizeMode(7, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_provider_overview_table.horizontalHeader().setSectionResizeMode(8, QHeaderView.ResizeMode.Stretch)
    self.ai_provider_overview_table.itemDoubleClicked.connect(self.switch_ai_provider_from_overview_item)
    self.ai_provider_overview_refresh_button = QPushButton("刷新厂商总览")
    self.ai_provider_overview_switch_button = QPushButton("切换到选中厂商")
    self.ai_provider_models_refresh_button = QPushButton("批量刷新模型")
    self.ai_provider_connectivity_test_button = QPushButton("一键测试模型")
    self.ai_provider_overview_refresh_button.clicked.connect(self.refresh_ai_provider_overview)
    self.ai_provider_overview_switch_button.clicked.connect(self.switch_ai_provider_from_overview)
    self.ai_provider_models_refresh_button.clicked.connect(self.refresh_all_ai_provider_models)
    self.ai_provider_connectivity_test_button.clicked.connect(self.test_all_ai_provider_connectivity)

    config_layout.addWidget(self.ai_provider_boundary_label, 0, 0, 1, 4)
    config_layout.addWidget(self.api_health_label, 1, 0, 1, 4)
    config_layout.addWidget(QLabel("厂商/接口"), 2, 0)
    config_layout.addWidget(self.ai_provider_combo, 2, 1)
    config_layout.addWidget(QLabel("接口格式"), 2, 2)
    config_layout.addWidget(self.ai_format_combo, 2, 3)
    config_layout.addWidget(QLabel("Base URL"), 3, 0)
    config_layout.addWidget(self.ai_base_url_input, 3, 1, 1, 3)
    config_layout.addWidget(QLabel("模型列表 URL"), 4, 0)
    config_layout.addWidget(self.ai_models_url_input, 4, 1, 1, 3)
    config_layout.addWidget(QLabel("模型搜索"), 5, 0)
    config_layout.addWidget(self.ai_model_search_input, 5, 1)
    config_layout.addWidget(QLabel("模型/动作"), 5, 2)
    config_layout.addWidget(self.ai_model_combo, 5, 3)
    config_layout.addWidget(self.ai_model_count_label, 6, 3)
    config_layout.addWidget(QLabel("用途预设"), 6, 0)
    config_layout.addWidget(self.ai_use_case_combo, 6, 1)
    config_layout.addWidget(self.ai_apply_use_case_button, 6, 2)
    config_layout.addWidget(self.ai_auto_apply_use_case_checkbox, 6, 3)
    config_layout.addWidget(self.ai_model_hint_label, 7, 0, 1, 4)
    config_layout.addWidget(QLabel("API Key"), 8, 0)
    config_layout.addWidget(self.ai_key_input, 8, 1)
    config_layout.addWidget(self.ai_save_button, 8, 2)
    config_layout.addWidget(self.ai_key_show_button, 8, 3)
    config_layout.addWidget(QLabel("Key 名称"), 9, 0)
    config_layout.addWidget(self.ai_key_name_input, 9, 1)
    config_layout.addWidget(self.ai_key_combo, 9, 2)
    config_layout.addWidget(self.ai_key_add_button, 9, 3)
    config_layout.addWidget(self.ai_key_delete_button, 10, 0)
    config_layout.addWidget(self.ai_key_use_available_button, 10, 1)
    config_layout.addWidget(self.ai_diagnose_button, 10, 2)
    config_layout.addWidget(self.ai_apply_preset_button, 10, 3)
    config_layout.addWidget(self.ai_test_button, 11, 2)
    config_layout.addWidget(self.ai_fetch_models_button, 11, 3)
    config_layout.addWidget(self.ai_cleanup_user_data_button, 12, 3)
    provider_overview_buttons = QHBoxLayout()
    provider_overview_buttons.addWidget(self.ai_provider_overview_refresh_button)
    provider_overview_buttons.addWidget(self.ai_provider_overview_switch_button)
    provider_overview_buttons.addWidget(self.ai_provider_models_refresh_button)
    provider_overview_buttons.addWidget(self.ai_provider_connectivity_test_button)
    provider_overview_buttons.addStretch(1)
    config_layout.addWidget(QLabel("厂商适配总览"), 13, 0)
    config_layout.addLayout(provider_overview_buttons, 13, 1, 1, 3)
    config_layout.addWidget(self.ai_provider_overview_table, 14, 0, 1, 4)

    workflow_box = QGroupBox("AI 抓取工作台")
    self.ai_workspace_box = workflow_box
    workflow_layout = QVBoxLayout(workflow_box)
    quick_box = QGroupBox("2 次点击网页转表格")
    self.ai_quick_scrape_box = quick_box
    quick_layout = QGridLayout(quick_box)
    depth_box = QGroupBox("高级设置：分页与子页面")
    self.ai_depth_scrape_box = depth_box
    depth_layout = QGridLayout(depth_box)
    agent_box = QGroupBox("高级设置：网页自动化 Agent")
    self.ai_agent_workspace_box = agent_box
    agent_layout = QGridLayout(agent_box)
    file_box = QGroupBox("高级设置：文件与线索工具")
    self.ai_file_tools_box = file_box
    file_layout = QGridLayout(file_box)
    self.advanced_ai_boxes = [depth_box, agent_box, file_box]
    for box in self.advanced_ai_boxes:
        box.setCheckable(True)
        box.setChecked(False)
        box.toggled.connect(self.apply_advanced_ai_visibility)
    self.ai_url_input = QLineEdit()
    self.ai_url_input.setPlaceholderText("要抓取的网址，留空则使用采集任务第一个网址")
    self.ai_prompt_input = QTextEdit()
    self.ai_prompt_input.setPlaceholderText("用中文描述要抓什么，例如：抓取产品名、价格、库存、详情页参数，并翻页 5 页")
    self.ai_prompt_input.setMaximumHeight(120)
    self.new_user_flow_label = QLabel("")
    self.new_user_flow_label.setWordWrap(True)
    self.wizard_scene_combo = QComboBox()
    for name in scene_template_presets().keys():
        self.wizard_scene_combo.addItem(name)
    self.wizard_configure_button = QPushButton("向导一键配置")
    self.ai_two_click_prepare_button = QPushButton("AI 一键准备")
    self.ai_two_click_start_button = QPushButton("准备并开始采集")
    self.ai_auto_fix_preflight_button = QPushButton("开始前自动修复")
    self.ai_suggest_button = QPushButton("AI 建议列")
    self.ai_preview_extract_button = QPushButton("预采一页")
    self.ai_repair_fields_button = QPushButton("AI 修复问题列")
    self.ai_task_button = QPushButton("生成采集任务")
    self.ai_agent_button = QPushButton("运行网页 Agent")
    self.ai_transform_button = QPushButton("AI 加工结果")
    self.ai_file_button = QPushButton("PDF/图片转表格")
    self.email_phone_button = QPushButton("提取邮箱/电话")
    self.image_download_button = QPushButton("下载图片")
    self.schedule_button = QPushButton("设置定时监控")
    self.scan_subpages_button = QPushButton("扫描子页面链接")
    self.apply_subpages_button = QPushButton("应用选中子页面")
    self.ai_next_page_selector_input = QLineEdit()
    self.ai_next_page_selector_input.setPlaceholderText("下一页按钮 CSS，可空；留空代表同页无限滚动")
    self.ai_page_limit_input = QSpinBox()
    self.ai_page_limit_input.setRange(1, 50)
    self.ai_page_limit_input.setValue(DEFAULT_PAGE_LIMIT)
    self.ai_scroll_times_input = QSpinBox()
    self.ai_scroll_times_input.setRange(0, 20)
    self.ai_scroll_times_input.setValue(DEFAULT_SCROLL_TIMES)
    self.preview_pagination_button = QPushButton("预览分页/滚动")
    self.apply_pagination_button = QPushButton("应用分页设置")
    self.ai_suggest_button.clicked.connect(self.ai_suggest_fields_for_current_url)
    self.ai_preview_extract_button.clicked.connect(self.preview_extract_current_page)
    self.ai_repair_fields_button.clicked.connect(self.ai_repair_problem_fields)
    self.ai_task_button.clicked.connect(self.ai_generate_task)
    self.ai_agent_button.clicked.connect(self.ai_run_agent)
    self.ai_transform_button.clicked.connect(self.ai_transform_current_records)
    self.ai_file_button.clicked.connect(self.ai_extract_file)
    self.email_phone_button.clicked.connect(self.extract_email_phone_current)
    self.image_download_button.clicked.connect(self.download_current_images)
    self.schedule_button.clicked.connect(self.show_schedule_hint)
    self.scan_subpages_button.clicked.connect(self.scan_subpage_links_for_current_url)
    self.apply_subpages_button.clicked.connect(self.apply_selected_subpage_links)
    self.preview_pagination_button.clicked.connect(self.preview_pagination_for_current_url)
    self.apply_pagination_button.clicked.connect(self.apply_pagination_settings)
    self.wizard_configure_button.clicked.connect(self.configure_collect_wizard)
    self.ai_two_click_prepare_button.clicked.connect(self.prepare_two_click_collect)
    self.ai_two_click_start_button.clicked.connect(self.prepare_and_start_collect)
    self.ai_auto_fix_preflight_button.clicked.connect(self.auto_fix_before_start)
    self.url_input.textChanged.connect(lambda: self.refresh_new_user_flow_status("input"))
    self.ai_url_input.textChanged.connect(lambda: self.refresh_new_user_flow_status("input"))
    quick_layout.addWidget(QLabel("网址"), 0, 0)
    quick_layout.addWidget(self.ai_url_input, 0, 1, 1, 4)
    quick_layout.addWidget(self.new_user_flow_label, 1, 0, 1, 5)
    quick_layout.addWidget(QLabel("场景"), 2, 0)
    quick_layout.addWidget(self.wizard_scene_combo, 2, 1)
    quick_layout.addWidget(self.wizard_configure_button, 2, 2)
    quick_layout.addWidget(self.ai_two_click_prepare_button, 2, 3)
    quick_layout.addWidget(self.ai_two_click_start_button, 2, 4)
    quick_layout.addWidget(QLabel("需求"), 3, 0)
    quick_layout.addWidget(self.ai_prompt_input, 3, 1, 1, 4)
    quick_layout.addWidget(self.ai_suggest_button, 4, 0)
    quick_layout.addWidget(self.ai_preview_extract_button, 4, 1)
    quick_layout.addWidget(self.ai_repair_fields_button, 4, 2)
    quick_layout.addWidget(self.ai_task_button, 4, 3)
    quick_layout.addWidget(self.ai_auto_fix_preflight_button, 4, 4)

    depth_layout.addWidget(QLabel("下一页 CSS"), 0, 0)
    depth_layout.addWidget(self.ai_next_page_selector_input, 0, 1, 1, 3)
    depth_layout.addWidget(QLabel("页数"), 1, 0)
    depth_layout.addWidget(self.ai_page_limit_input, 1, 1)
    depth_layout.addWidget(QLabel("滚动"), 1, 2)
    depth_layout.addWidget(self.ai_scroll_times_input, 1, 3)
    depth_layout.addWidget(self.preview_pagination_button, 2, 0)
    depth_layout.addWidget(self.apply_pagination_button, 2, 1)
    depth_layout.addWidget(self.scan_subpages_button, 2, 2)
    depth_layout.addWidget(self.apply_subpages_button, 2, 3)

    agent_layout.addWidget(self.ai_agent_button, 0, 0)
    agent_layout.addWidget(self.ai_transform_button, 0, 1)
    agent_layout.addWidget(self.schedule_button, 0, 2)
    agent_layout.setColumnStretch(3, 1)

    file_layout.addWidget(self.ai_file_button, 0, 0)
    file_layout.addWidget(self.email_phone_button, 0, 1)
    file_layout.addWidget(self.image_download_button, 0, 2)
    file_layout.setColumnStretch(3, 1)

    workflow_layout.addWidget(quick_box)
    workflow_layout.addWidget(depth_box)
    workflow_layout.addWidget(agent_box)
    workflow_layout.addWidget(file_box)
    self.apply_advanced_ai_visibility()
    self.refresh_new_user_flow_status("input")

    left = QWidget()
    left_layout = QVBoxLayout(left)
    left_layout.addWidget(config_box)
    left_layout.addWidget(workflow_box)
    left_layout.addStretch(1)

    output_box = QGroupBox("AI 输出 / 表格预览")
    output_layout = QVBoxLayout(output_box)
    self.ai_output = QPlainTextEdit()
    self.ai_output.setReadOnly(True)
    self.ai_table = QTableWidget(0, 0)
    self.ai_table.verticalHeader().setVisible(False)
    self.ai_quality_score_label = QLabel("字段质量评分：等待预采")
    self.ai_quality_score_label.setWordWrap(True)
    self.result_quality_score_label = QLabel("采集结果质量：等待结果")
    self.result_quality_score_label.setWordWrap(True)
    self.repair_quality_report_label = QLabel("AI 修复验证：等待修复")
    self.repair_quality_report_label.setWordWrap(True)
    self.ai_apply_repaired_fields_button = QPushButton("应用 AI 修复到模板")
    self.ai_apply_repaired_fields_button.clicked.connect(self.apply_repaired_fields_to_template)
    self.result_quality_repair_button = QPushButton("用结果质量修复字段")
    self.result_quality_repair_button.clicked.connect(self.ai_repair_from_result_quality)
    self.ai_quality_table = QTableWidget(0, 6)
    self.ai_quality_table.setHorizontalHeaderLabels(["状态", "评分", "字段名", "问题", "建议", "选择器"])
    self.ai_quality_table.verticalHeader().setVisible(False)
    self.ai_quality_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_quality_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_quality_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_quality_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_quality_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.Stretch)
    self.ai_quality_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.Stretch)
    self.result_quality_table = QTableWidget(0, 7)
    self.result_quality_table.setHorizontalHeaderLabels(["状态", "评分", "字段", "空值", "重复", "问题", "建议"])
    self.result_quality_table.verticalHeader().setVisible(False)
    self.result_quality_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.result_quality_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.result_quality_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.result_quality_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.result_quality_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.result_quality_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.Stretch)
    self.result_quality_table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.Stretch)
    self.repair_quality_report_table = QTableWidget(0, 9)
    self.repair_quality_report_table.setHorizontalHeaderLabels(["字段", "样本数", "修复前", "修复后", "分数变化", "状态变化", "问题变化", "建议", "结论"])
    self.repair_quality_report_table.verticalHeader().setVisible(False)
    self.repair_quality_report_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.repair_quality_report_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.repair_quality_report_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.repair_quality_report_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.repair_quality_report_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.repair_quality_report_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.ResizeToContents)
    self.repair_quality_report_table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.Stretch)
    self.repair_quality_report_table.horizontalHeader().setSectionResizeMode(7, QHeaderView.ResizeMode.Stretch)
    self.repair_quality_report_table.horizontalHeader().setSectionResizeMode(8, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_repair_history_table = QTableWidget(0, 10)
    self.ai_repair_history_table.setHorizontalHeaderLabels(
        ["时间", "厂商", "模型", "样本数", "字段数", "改善", "持平", "变差", "平均变化", "失败字段"]
    )
    self.ai_repair_history_table.verticalHeader().setVisible(False)
    for column in range(9):
        self.ai_repair_history_table.horizontalHeader().setSectionResizeMode(column, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_repair_history_table.horizontalHeader().setSectionResizeMode(9, QHeaderView.ResizeMode.Stretch)
    self.ai_repair_diff_table = QTableWidget(0, 6)
    self.ai_repair_diff_table.setHorizontalHeaderLabels(["变化", "字段", "当前选择器", "历史选择器", "当前取值", "历史取值"])
    self.ai_repair_diff_table.verticalHeader().setVisible(False)
    self.ai_repair_diff_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
    self.ai_repair_diff_table.setSelectionMode(QTableWidget.SelectionMode.MultiSelection)
    self.ai_repair_diff_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_repair_diff_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_repair_diff_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
    self.ai_repair_diff_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.Stretch)
    self.ai_repair_diff_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_repair_diff_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_diagnosis_table = QTableWidget(0, 4)
    self.ai_diagnosis_table.setHorizontalHeaderLabels(["级别", "检查项", "状态", "修复建议"])
    self.ai_diagnosis_table.verticalHeader().setVisible(False)
    self.ai_diagnosis_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_diagnosis_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_diagnosis_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
    self.ai_diagnosis_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.Stretch)
    self.ai_call_log_table = QTableWidget(0, 9)
    self.ai_call_log_table.setHorizontalHeaderLabels(["时间", "动作", "状态", "厂商", "模型", "Key", "耗时ms", "自动切换", "错误"])
    self.ai_call_log_table.verticalHeader().setVisible(False)
    self.ai_call_log_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_call_log_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_call_log_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_call_log_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_call_log_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_call_log_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_call_log_table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_call_log_table.horizontalHeader().setSectionResizeMode(7, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_call_log_table.horizontalHeader().setSectionResizeMode(8, QHeaderView.ResizeMode.Stretch)
    self.ai_call_summary_table = QTableWidget(0, 10)
    self.ai_call_summary_table.setHorizontalHeaderLabels(
        ["厂商", "模型", "Key", "总次数", "成功", "失败", "成功率", "平均耗时ms", "自动切换", "最近错误"]
    )
    self.ai_call_summary_table.verticalHeader().setVisible(False)
    for column in range(9):
        self.ai_call_summary_table.horizontalHeader().setSectionResizeMode(column, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_call_summary_table.horizontalHeader().setSectionResizeMode(9, QHeaderView.ResizeMode.Stretch)
    self.ai_refresh_call_logs_button = QPushButton("刷新调用日志")
    self.ai_export_call_logs_button = QPushButton("导出调用日志")
    self.ai_clear_call_logs_button = QPushButton("清空调用日志")
    self.ai_refresh_call_summary_button = QPushButton("刷新用量汇总")
    self.ai_export_call_summary_button = QPushButton("导出用量汇总")
    self.ai_refresh_repair_history_button = QPushButton("刷新修复历史")
    self.ai_export_repair_history_button = QPushButton("导出修复历史")
    self.ai_apply_best_repair_history_button = QPushButton("复用最佳修复")
    self.ai_apply_selected_repair_history_button = QPushButton("复用选中修复")
    self.ai_compare_selected_repair_history_button = QPushButton("对比选中修复")
    self.ai_apply_selected_repair_fields_button = QPushButton("只应用对比选中字段")
    self.ai_refresh_call_logs_button.clicked.connect(self.refresh_ai_call_logs)
    self.ai_export_call_logs_button.clicked.connect(self.export_ai_call_logs)
    self.ai_clear_call_logs_button.clicked.connect(self.confirm_clear_ai_call_logs)
    self.ai_refresh_call_summary_button.clicked.connect(self.refresh_ai_call_summary)
    self.ai_export_call_summary_button.clicked.connect(self.export_ai_call_summary)
    self.ai_refresh_repair_history_button.clicked.connect(self.refresh_ai_repair_history)
    self.ai_export_repair_history_button.clicked.connect(self.export_ai_repair_history)
    self.ai_apply_best_repair_history_button.clicked.connect(self.apply_best_ai_repair_history)
    self.ai_apply_selected_repair_history_button.clicked.connect(self.apply_selected_ai_repair_history)
    self.ai_compare_selected_repair_history_button.clicked.connect(self.compare_selected_ai_repair_history)
    self.ai_apply_selected_repair_fields_button.clicked.connect(self.apply_selected_ai_repair_fields)
    self.ai_repair_history_table.itemSelectionChanged.connect(self.compare_selected_ai_repair_history)
    plan_buttons = QHBoxLayout()
    self.ai_apply_task_plan_button = QPushButton("应用计划到采集任务")
    self.ai_run_task_plan_button = QPushButton("执行计划 Agent")
    self.ai_copy_task_plan_button = QPushButton("复制计划 JSON")
    self.ai_apply_task_plan_button.clicked.connect(self.apply_current_ai_task_plan)
    self.ai_run_task_plan_button.clicked.connect(self.ai_run_agent)
    self.ai_copy_task_plan_button.clicked.connect(self.copy_current_ai_task_plan)
    plan_buttons.addWidget(self.ai_apply_task_plan_button)
    plan_buttons.addWidget(self.ai_run_task_plan_button)
    plan_buttons.addWidget(self.ai_copy_task_plan_button)
    plan_buttons.addStretch(1)
    suggest_buttons = QHBoxLayout()
    self.ai_apply_fields_button = QPushButton("应用选中建议列")
    self.ai_select_all_fields_button = QPushButton("全选建议列")
    self.ai_clear_fields_button = QPushButton("清空建议列")
    self.ai_apply_fields_button.clicked.connect(self.apply_checked_ai_fields_to_template)
    self.ai_select_all_fields_button.clicked.connect(self.select_all_ai_suggested_fields)
    self.ai_clear_fields_button.clicked.connect(self.clear_ai_suggested_fields)
    suggest_buttons.addWidget(self.ai_apply_fields_button)
    suggest_buttons.addWidget(self.ai_select_all_fields_button)
    suggest_buttons.addWidget(self.ai_clear_fields_button)
    suggest_buttons.addStretch(1)
    table_buttons = QHBoxLayout()
    self.ai_export_table_button = QPushButton("导出 AI 表格")
    self.ai_copy_table_button = QPushButton("复制 AI 表格")
    self.ai_export_table_button.clicked.connect(self.export_ai_table)
    self.ai_copy_table_button.clicked.connect(self.copy_ai_table_to_clipboard)
    table_buttons.addWidget(self.ai_export_table_button)
    table_buttons.addWidget(self.ai_copy_table_button)
    table_buttons.addWidget(self.ai_refresh_call_logs_button)
    table_buttons.addWidget(self.ai_export_call_logs_button)
    table_buttons.addWidget(self.ai_refresh_call_summary_button)
    table_buttons.addWidget(self.ai_export_call_summary_button)
    table_buttons.addWidget(self.ai_refresh_repair_history_button)
    table_buttons.addWidget(self.ai_export_repair_history_button)
    table_buttons.addWidget(self.ai_apply_best_repair_history_button)
    table_buttons.addWidget(self.ai_apply_selected_repair_history_button)
    table_buttons.addWidget(self.ai_compare_selected_repair_history_button)
    table_buttons.addWidget(self.ai_apply_selected_repair_fields_button)
    table_buttons.addWidget(self.ai_clear_call_logs_button)
    table_buttons.addStretch(1)
    self.ai_suggest_table = QTableWidget(0, 6)
    self.ai_suggest_table.setHorizontalHeaderLabels(["启用", "字段名", "CSS 选择器", "取值", "多条", "理由"])
    self.ai_suggest_table.verticalHeader().setVisible(False)
    self.ai_suggest_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_suggest_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_suggest_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
    self.ai_suggest_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_suggest_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_suggest_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_task_plan_label = QLabel("自然语言任务计划：等待生成")
    self.ai_task_plan_label.setWordWrap(True)
    self.ai_task_plan_table = QTableWidget(0, 4)
    self.ai_task_plan_table.setHorizontalHeaderLabels(["类型", "项目", "参数", "说明"])
    self.ai_task_plan_table.verticalHeader().setVisible(False)
    self.ai_task_plan_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_task_plan_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.ai_task_plan_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
    self.ai_task_plan_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.Stretch)
    self.subpage_link_table = QTableWidget(0, 6)
    self.subpage_link_table.setHorizontalHeaderLabels(["深抓", "类型", "链接文字", "URL", "原因", "分数"])
    self.subpage_link_table.verticalHeader().setVisible(False)
    self.subpage_link_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.subpage_link_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.subpage_link_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.subpage_link_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.Stretch)
    self.subpage_link_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.subpage_link_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.ResizeToContents)
    self.pagination_table = QTableWidget(0, 5)
    self.pagination_table.setHorizontalHeaderLabels(["序号", "模式", "将采集 URL", "滚动次数", "状态"])
    self.pagination_table.verticalHeader().setVisible(False)
    self.pagination_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.pagination_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.pagination_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
    self.pagination_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.pagination_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    output_layout.addWidget(self.ai_output, 1)
    output_layout.addWidget(self.ai_task_plan_label)
    output_layout.addLayout(plan_buttons)
    output_layout.addWidget(self.ai_task_plan_table, 2)
    output_layout.addLayout(suggest_buttons)
    output_layout.addWidget(self.ai_suggest_table, 2)
    output_layout.addWidget(self.pagination_table, 2)
    output_layout.addWidget(self.subpage_link_table, 2)
    quality_buttons = QHBoxLayout()
    quality_buttons.addWidget(self.ai_quality_score_label)
    quality_buttons.addWidget(self.ai_apply_repaired_fields_button)
    quality_buttons.addStretch(1)
    output_layout.addLayout(quality_buttons)
    output_layout.addWidget(self.ai_quality_table, 1)
    result_quality_buttons = QHBoxLayout()
    result_quality_buttons.addWidget(self.result_quality_score_label)
    result_quality_buttons.addWidget(self.result_quality_repair_button)
    result_quality_buttons.addStretch(1)
    output_layout.addLayout(result_quality_buttons)
    output_layout.addWidget(self.result_quality_table, 1)
    output_layout.addWidget(self.repair_quality_report_label)
    output_layout.addWidget(self.repair_quality_report_table, 1)
    output_layout.addWidget(self.ai_diagnosis_table, 1)
    output_layout.addWidget(self.ai_repair_history_table, 1)
    output_layout.addWidget(self.ai_repair_diff_table, 1)
    output_layout.addWidget(self.ai_call_summary_table, 1)
    output_layout.addWidget(self.ai_call_log_table, 1)
    output_layout.addLayout(table_buttons)
    output_layout.addWidget(self.ai_table, 2)

    splitter.addWidget(left)
    splitter.addWidget(output_box)
    splitter.setStretchFactor(0, 2)
    splitter.setStretchFactor(1, 3)
    layout.addWidget(splitter)
    self.load_ai_settings_to_ui()
    return page

