"""History, monitoring, and run archive tab construction for the universal UI."""

from ui_registry import register

from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (
    QComboBox,
    QGroupBox,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QPlainTextEdit,
    QPushButton,
    QSplitter,
    QTableWidget,
    QTabWidget,
    QTextEdit,
    QVBoxLayout,
    QWidget,
    QComboBox,
    QGroupBox,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QPlainTextEdit,
    QPushButton,
    QSplitter,
    QTabWidget,
    QTableWidget,
    QTextEdit,
    QVBoxLayout,
    QWidget,

)

@register("build_history_tab")
def build_history_tab(self):
    page = QWidget()
    layout = QVBoxLayout(page)
    layout.setContentsMargins(12, 12, 12, 12)
    layout.setSpacing(10)
    summary_box = QGroupBox("历史与监控总览")
    summary_layout = QVBoxLayout(summary_box)
    summary_layout.addWidget(QLabel("这里集中查看采集历史、任务档案、变更提醒、变更报告与计划采集。"))
    summary_layout.addWidget(QLabel("新版布局保持所有原功能入口不变，只优化查阅顺序和信息分区。"))
    layout.addWidget(summary_box)
    buttons = QHBoxLayout()
    self.reload_history_button = QPushButton("刷新历史")
    self.export_history_button = QPushButton("导出历史")
    self.copy_history_sheets_button = QPushButton("复制历史到 Sheets")
    self.generate_change_report_button = QPushButton("生成变更报告")
    self.export_change_report_button = QPushButton("导出变更报告")
    self.refresh_change_alerts_button = QPushButton("刷新变更提醒")
    self.export_change_alerts_button = QPushButton("导出变更提醒")
    self.change_alert_mark_handled_button = QPushButton("标记已处理")
    self.change_alert_mark_ignored_button = QPushButton("忽略提醒")
    self.change_alert_mark_unread_button = QPushButton("标回未读")
    self.export_runs_button = QPushButton("导出任务档案")
    self.reuse_run_button = QPushButton("复用任务配置")
    self.rerun_task_button = QPushButton("按此任务重跑")
    self.resume_run_queue_button = QPushButton("继续失败/未完成")
    self.add_schedule_button = QPushButton("新增计划采集")
    self.toggle_schedule_button = QPushButton("启停计划")
    self.run_schedule_now_button = QPushButton("立即运行计划")
    self.delete_schedule_button = QPushButton("删除计划")
    self.reload_history_button.clicked.connect(self.load_recent_records)
    self.export_history_button.clicked.connect(self.export_history_results)
    self.copy_history_sheets_button.clicked.connect(self.copy_history_results_to_sheets)
    self.generate_change_report_button.clicked.connect(self.generate_change_report)
    self.export_change_report_button.clicked.connect(self.export_change_report)
    self.refresh_change_alerts_button.clicked.connect(self.refresh_change_alerts)
    self.export_change_alerts_button.clicked.connect(self.export_change_alerts)
    self.change_alert_mark_handled_button.clicked.connect(lambda: self.set_selected_change_alert_status("已处理"))
    self.change_alert_mark_ignored_button.clicked.connect(lambda: self.set_selected_change_alert_status("忽略"))
    self.change_alert_mark_unread_button.clicked.connect(lambda: self.set_selected_change_alert_status("未读"))
    self.export_runs_button.clicked.connect(self.export_run_records)
    self.reuse_run_button.clicked.connect(self.reuse_selected_run_config)
    self.rerun_task_button.clicked.connect(self.rerun_selected_task)
    self.resume_run_queue_button.clicked.connect(self.resume_selected_run_queue)
    self.add_schedule_button.clicked.connect(self.add_schedule_from_current_config)
    self.toggle_schedule_button.clicked.connect(self.toggle_selected_schedule)
    self.run_schedule_now_button.clicked.connect(self.run_selected_schedule_now)
    self.delete_schedule_button.clicked.connect(self.delete_selected_schedule)
    buttons.addWidget(self.reload_history_button)
    buttons.addWidget(self.export_history_button)
    buttons.addWidget(self.copy_history_sheets_button)
    buttons.addWidget(self.generate_change_report_button)
    buttons.addWidget(self.export_change_report_button)
    buttons.addWidget(self.refresh_change_alerts_button)
    buttons.addWidget(self.export_change_alerts_button)
    buttons.addWidget(self.change_alert_mark_handled_button)
    buttons.addWidget(self.change_alert_mark_ignored_button)
    buttons.addWidget(self.change_alert_mark_unread_button)
    buttons.addWidget(self.export_runs_button)
    buttons.addWidget(self.reuse_run_button)
    buttons.addWidget(self.rerun_task_button)
    buttons.addWidget(self.resume_run_queue_button)
    buttons.addWidget(self.add_schedule_button)
    buttons.addWidget(self.toggle_schedule_button)
    buttons.addWidget(self.run_schedule_now_button)
    buttons.addWidget(self.delete_schedule_button)
    buttons.addStretch(1)
    self.history_table = self.create_result_table()
    self.history_table.itemSelectionChanged.connect(self.update_history_detail)
    self.change_report_table = QTableWidget(0, 7)
    self.change_report_table.setHorizontalHeaderLabels(["监控时间", "网址", "域名", "字段", "旧值", "新值", "标题"])
    self.change_report_table.verticalHeader().setVisible(False)
    self.change_report_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.change_report_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
    self.change_report_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.change_report_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.change_report_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.Stretch)
    self.change_report_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.Stretch)
    self.change_report_table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.ResizeToContents)
    self.change_alert_status_label = QLabel("暂无变更提醒")
    self.change_alert_status_label.setWordWrap(True)
    self.change_alert_filter_combo = QComboBox()
    self.change_alert_filter_combo.addItems(["全部提醒", "未读", "已处理", "忽略"])
    self.change_alert_filter_combo.currentIndexChanged.connect(lambda: self.fill_change_alert_table(self.change_alert_rows))
    self.change_alert_table = QTableWidget(0, 10)
    self.change_alert_table.setHorizontalHeaderLabels(["处理状态", "类型", "监控时间", "网址", "字段", "旧值", "新值", "标题", "域名", "ID"])
    self.change_alert_table.verticalHeader().setVisible(False)
    self.change_alert_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
    self.change_alert_table.setSelectionMode(QTableWidget.SelectionMode.SingleSelection)
    self.change_alert_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.change_alert_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.change_alert_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.change_alert_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.change_alert_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.Stretch)
    self.change_alert_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.Stretch)
    self.change_alert_table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.Stretch)
    self.change_alert_table.horizontalHeader().setSectionResizeMode(7, QHeaderView.ResizeMode.ResizeToContents)
    self.change_alert_table.horizontalHeader().setSectionResizeMode(8, QHeaderView.ResizeMode.ResizeToContents)
    self.change_alert_table.horizontalHeader().setSectionResizeMode(9, QHeaderView.ResizeMode.ResizeToContents)
    self.run_table = QTableWidget(0, 9)
    self.run_table.setHorizontalHeaderLabels(["ID", "开始时间", "结束时间", "状态", "网址数", "模板", "AI 厂商", "模型", "结果数"])
    self.run_table.verticalHeader().setVisible(False)
    self.run_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
    self.run_table.setSelectionMode(QTableWidget.SelectionMode.SingleSelection)
    self.run_table.itemSelectionChanged.connect(self.update_run_detail)
    self.run_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.run_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.run_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.run_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.run_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.run_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.ResizeToContents)
    self.run_table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.ResizeToContents)
    self.run_table.horizontalHeader().setSectionResizeMode(7, QHeaderView.ResizeMode.Stretch)
    self.run_table.horizontalHeader().setSectionResizeMode(8, QHeaderView.ResizeMode.ResizeToContents)
    self.memory_topic_table = QTableWidget(0, 4)
    self.memory_topic_table.setHorizontalHeaderLabels(["ID", "主题", "摘要", "更新时间"])
    self.memory_topic_table.verticalHeader().setVisible(False)
    self.memory_topic_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
    self.memory_topic_table.setSelectionMode(QTableWidget.SelectionMode.SingleSelection)
    self.memory_topic_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.memory_topic_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.memory_topic_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
    self.memory_topic_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.memory_related_table = QTableWidget(0, 4)
    self.memory_related_table.setHorizontalHeaderLabels(["关系", "标题", "来源", "实体键"])
    self.memory_related_table.verticalHeader().setVisible(False)
    self.memory_related_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.memory_related_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
    self.memory_related_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
    self.memory_related_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.memory_detail_output = QPlainTextEdit()
    self.memory_detail_output.setReadOnly(True)
    self.memory_item_table = QTableWidget(0, 6)
    self.memory_item_table.setHorizontalHeaderLabels(["类型", "标题", "摘要", "来源", "关系", "实体键"])
    self.memory_item_table.verticalHeader().setVisible(False)
    self.memory_item_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.memory_item_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.memory_item_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
    self.memory_item_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.Stretch)
    self.memory_item_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.memory_item_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.ResizeToContents)
    self.schedule_table = QTableWidget(0, 9)
    self.schedule_table.setHorizontalHeaderLabels(["状态", "计划名", "间隔", "下次运行", "上次运行", "次数", "结果", "网址数", "ID"])
    self.schedule_table.verticalHeader().setVisible(False)
    self.schedule_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
    self.schedule_table.setSelectionMode(QTableWidget.SelectionMode.SingleSelection)
    self.schedule_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.schedule_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
    self.schedule_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.schedule_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.schedule_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.schedule_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.ResizeToContents)
    self.schedule_table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.Stretch)
    self.schedule_table.horizontalHeader().setSectionResizeMode(7, QHeaderView.ResizeMode.ResizeToContents)
    self.schedule_table.horizontalHeader().setSectionResizeMode(8, QHeaderView.ResizeMode.ResizeToContents)
    history_splitter = QSplitter(Qt.Orientation.Horizontal)
    history_splitter.addWidget(self.history_table)
    history_splitter.addWidget(self.build_history_detail_panel())
    history_splitter.setStretchFactor(0, 3)
    history_splitter.setStretchFactor(1, 2)
    self.history_sections_tabs = QTabWidget()
    self.history_sections_tabs.addTab(history_splitter, "采集历史")
    run_page = QWidget()
    run_layout = QVBoxLayout(run_page)
    run_splitter = QSplitter(Qt.Orientation.Horizontal)
    run_table_panel = QWidget()
    run_table_layout = QVBoxLayout(run_table_panel)
    run_layout.addWidget(QLabel("任务运行档案 / 配置快照"))
    run_table_layout.addWidget(self.run_table)
    run_splitter.addWidget(run_table_panel)
    run_splitter.addWidget(self.build_run_detail_panel())
    run_splitter.setStretchFactor(0, 3)
    run_splitter.setStretchFactor(1, 2)
    run_layout.addWidget(run_splitter)
    self.history_sections_tabs.addTab(run_page, "任务档案")
    alert_page = QWidget()
    alert_layout = QVBoxLayout(alert_page)
    alert_summary = QGroupBox("提醒概览")
    alert_summary_layout = QVBoxLayout(alert_summary)
    alert_summary_layout.addWidget(self.change_alert_status_label)
    alert_summary_layout.addWidget(self.change_alert_filter_combo)
    alert_layout.addWidget(alert_summary)
    alert_layout.addWidget(self.change_alert_table)
    self.history_sections_tabs.addTab(alert_page, "变更提醒")
    change_page = QWidget()
    change_layout = QVBoxLayout(change_page)
    change_header = QGroupBox("变更报告总览")
    change_header_layout = QVBoxLayout(change_header)
    change_header_layout.addWidget(QLabel("用于快速查看字段变化、旧值/新值和监控时间。"))
    change_layout.addWidget(change_header)
    change_layout.addWidget(self.change_report_table)
    self.history_sections_tabs.addTab(change_page, "变更报告")
    schedule_page = QWidget()
    schedule_layout = QVBoxLayout(schedule_page)
    schedule_header = QGroupBox("计划采集")
    schedule_header_layout = QVBoxLayout(schedule_header)
    schedule_header_layout.addWidget(QLabel("集中管理定时任务、启停状态和最近运行结果。"))
    schedule_layout.addWidget(schedule_header)
    schedule_layout.addWidget(self.schedule_table)
    self.history_sections_tabs.addTab(schedule_page, "计划采集")
    memory_page = QWidget()
    memory_layout = QVBoxLayout(memory_page)
    memory_header = QGroupBox("记忆宫殿")
    memory_header_layout = QVBoxLayout(memory_header)
    memory_header_layout.addWidget(QLabel("记忆宫殿默认在后台全自动运行：自动建主题、自动同步、自动关联、自动摘要。下面按钮仅用于维护或补救。"))
    self.memory_archive_current_button = QPushButton("维护：手动归入主题")
    self.memory_enable_sync_button = QPushButton("维护：开启自动同步")
    self.memory_mark_synced_button = QPushButton("维护：标记已同步")
    self.memory_run_sync_button = QPushButton("维护：立即同步主题")
    self.memory_refresh_button = QPushButton("刷新记忆宫殿")
    self.memory_archive_current_button.clicked.connect(self.archive_current_records_to_memory_topic)
    self.memory_enable_sync_button.clicked.connect(self.enable_selected_memory_topic_sync)
    self.memory_mark_synced_button.clicked.connect(self.mark_selected_memory_topic_synced)
    self.memory_run_sync_button.clicked.connect(self.run_selected_memory_topic_sync)
    self.memory_refresh_button.clicked.connect(self.refresh_memory_palace)
    memory_button_row = QHBoxLayout()
    memory_button_row.addWidget(self.memory_archive_current_button)
    memory_button_row.addWidget(self.memory_enable_sync_button)
    memory_button_row.addWidget(self.memory_mark_synced_button)
    memory_button_row.addWidget(self.memory_run_sync_button)
    memory_button_row.addWidget(self.memory_refresh_button)
    memory_button_row.addStretch(1)
    memory_header_layout.addLayout(memory_button_row)
    memory_layout.addWidget(memory_header)
    memory_splitter = QSplitter(Qt.Orientation.Horizontal)
    memory_right_panel = QWidget()
    memory_right_layout = QVBoxLayout(memory_right_panel)
    memory_right_layout.addWidget(self.memory_item_table)
    memory_right_layout.addWidget(QLabel("交叉引用详情"))
    memory_right_layout.addWidget(self.memory_related_table)
    memory_right_layout.addWidget(self.memory_detail_output)
    memory_splitter.addWidget(self.memory_topic_table)
    memory_splitter.addWidget(memory_right_panel)
    memory_splitter.setStretchFactor(0, 2)
    memory_splitter.setStretchFactor(1, 3)
    memory_layout.addWidget(memory_splitter)
    self.history_sections_tabs.addTab(memory_page, "记忆宫殿")
    action_box = QGroupBox("快捷操作")
    action_layout = QVBoxLayout(action_box)
    action_layout.addLayout(buttons)
    layout.addWidget(action_box)
    layout.addWidget(self.history_sections_tabs)
    self.fill_schedule_table()
    self.refresh_change_alerts(silent=True)
    return page

@register("build_history_detail_panel")
def build_history_detail_panel(self):
    panel = QWidget()
    layout = QVBoxLayout(panel)
    self.history_detail_title_label = QLabel("未选择历史记录")
    self.history_detail_title_label.setWordWrap(True)
    self.history_detail_body_output = QTextEdit()
    self.history_detail_body_output.setReadOnly(True)
    self.history_detail_link_table = QTableWidget(0, 2)
    self.history_detail_link_table.setHorizontalHeaderLabels(["文字", "链接"])
    self.history_detail_link_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.history_detail_link_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
    self.history_detail_table_view = QTableWidget(0, 0)
    layout.addWidget(QLabel("历史详情"))
    layout.addWidget(self.history_detail_title_label)
    layout.addWidget(self.history_detail_body_output)
    layout.addWidget(QLabel("链接"))
    layout.addWidget(self.history_detail_link_table)
    layout.addWidget(QLabel("表格"))
    layout.addWidget(self.history_detail_table_view)
    return panel

@register("build_run_detail_panel")
def build_run_detail_panel(self):
    panel = QWidget()
    layout = QVBoxLayout(panel)
    self.run_detail_title_label = QLabel("未选择任务档案")
    self.run_detail_title_label.setWordWrap(True)
    self.run_detail_summary_output = QPlainTextEdit()
    self.run_detail_summary_output.setReadOnly(True)
    self.run_detail_summary_output.setMaximumHeight(120)
    self.run_detail_url_table = QTableWidget(0, 1)
    self.run_detail_url_table.setHorizontalHeaderLabels(["网址"])
    self.run_detail_url_table.verticalHeader().setVisible(False)
    self.run_detail_url_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
    self.run_detail_risk_table = QTableWidget(0, 5)
    self.run_detail_risk_table.setHorizontalHeaderLabels(["级别", "检查项", "说明", "建议", "参考"])
    self.run_detail_risk_table.verticalHeader().setVisible(False)
    self.run_detail_risk_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.run_detail_risk_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.run_detail_risk_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
    self.run_detail_risk_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.Stretch)
    self.run_detail_risk_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.run_detail_queue_table = QTableWidget(0, 8)
    self.run_detail_queue_table.setHorizontalHeaderLabels(["状态", "类型", "阶段", "网址", "结果数", "错误类型", "建议", "错误"])
    self.run_detail_queue_table.verticalHeader().setVisible(False)
    self.run_detail_queue_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
    self.run_detail_queue_table.setSelectionMode(QTableWidget.SelectionMode.SingleSelection)
    self.run_detail_queue_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.run_detail_queue_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.run_detail_queue_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.run_detail_queue_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.Stretch)
    self.run_detail_queue_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
    self.run_detail_queue_table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.ResizeToContents)
    self.run_detail_queue_table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.Stretch)
    self.run_detail_queue_table.horizontalHeader().setSectionResizeMode(7, QHeaderView.ResizeMode.Stretch)
    self.run_detail_queue_table.setMaximumHeight(160)
    self.run_detail_result_table = self.create_result_table()
    self.run_detail_result_table.setMaximumHeight(180)
    self.export_run_results_button = QPushButton("导出当前任务结果")
    self.view_run_queue_result_button = QPushButton("查看队列对应结果")
    self.export_run_results_button.clicked.connect(self.export_selected_run_results)
    self.view_run_queue_result_button.clicked.connect(self.view_selected_run_queue_result)
    self.run_detail_json_output = QPlainTextEdit()
    self.run_detail_json_output.setReadOnly(True)
    layout.addWidget(QLabel("任务详情"))
    layout.addWidget(self.run_detail_title_label)
    layout.addWidget(QLabel("摘要"))
    layout.addWidget(self.run_detail_summary_output)
    layout.addWidget(QLabel("网址列表"))
    layout.addWidget(self.run_detail_url_table)
    layout.addWidget(QLabel("风险检查"))
    layout.addWidget(self.run_detail_risk_table)
    layout.addWidget(QLabel("任务队列快照"))
    layout.addWidget(self.run_detail_queue_table)
    layout.addWidget(QLabel("本次采集结果"))
    layout.addWidget(self.export_run_results_button)
    layout.addWidget(self.view_run_queue_result_button)
    layout.addWidget(self.run_detail_result_table)
    layout.addWidget(QLabel("完整配置 JSON"))
    layout.addWidget(self.run_detail_json_output)
    return panel
