"""Template tab construction for the universal UI."""

from ui_registry import register

from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QComboBox, QGridLayout, QGroupBox, QHBoxLayout, QHeaderView, QLabel, QLineEdit, QListWidget, QPushButton, QSplitter, QTableWidget, QTextEdit, QVBoxLayout, QWidget

from universal_core import TEMPLATE_TYPES, scene_template_presets


@register("build_template_tab")
def build_template_tab(self):
    page = QWidget()
    layout = QVBoxLayout(page)
    splitter = QSplitter(Qt.Orientation.Horizontal)

    left = QWidget()
    left_layout = QVBoxLayout(left)
    self.template_list = QListWidget()
    self.template_list.currentRowChanged.connect(self.load_template_to_editor)
    self.template_market_search_input = QLineEdit()
    self.template_market_search_input.setPlaceholderText("搜索行业、字段或用途，例如 电商 / 邮箱 / 图片 / 房产")
    self.template_market_category_combo = QComboBox()
    self.template_market_recommend_label = QLabel("模板市场：等待网址分析")
    self.template_market_recommend_label.setWordWrap(True)
    self.template_market_table = QTableWidget(0, 5)
    self.template_market_table.setHorizontalHeaderLabels(["分类", "模板", "字段数", "模型用途", "说明"])
    self.template_market_table.verticalHeader().setVisible(False)
    self.template_market_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.template_market_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
    self.template_market_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.template_market_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    self.template_market_table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.Stretch)
    self.template_market_install_button = QPushButton("安装选中模板")
    self.template_market_apply_button = QPushButton("安装并用于当前任务")
    self.template_market_search_input.textChanged.connect(self.refresh_template_market)
    self.template_market_category_combo.currentIndexChanged.connect(self.refresh_template_market)
    self.template_market_install_button.clicked.connect(lambda: self.install_market_template(False))
    self.template_market_apply_button.clicked.connect(lambda: self.install_market_template(True))
    self.scene_preset_combo = QComboBox()
    self.apply_scene_preset_button = QPushButton("一键套用场景")
    self.apply_scene_preset_button.clicked.connect(self.apply_scene_preset)
    for name in scene_template_presets().keys():
        self.scene_preset_combo.addItem(name)
    template_buttons = QHBoxLayout()
    self.new_template_button = QPushButton("新建模板")
    self.save_template_button = QPushButton("保存模板")
    self.delete_template_button = QPushButton("删除模板")
    self.new_template_button.clicked.connect(self.new_template)
    self.save_template_button.clicked.connect(self.save_current_template)
    self.delete_template_button.clicked.connect(self.delete_current_template)
    template_buttons.addWidget(self.new_template_button)
    template_buttons.addWidget(self.save_template_button)
    template_buttons.addWidget(self.delete_template_button)
    left_layout.addWidget(self.template_list)
    left_layout.addWidget(QLabel("模板市场"))
    left_layout.addWidget(self.template_market_recommend_label)
    left_layout.addWidget(self.template_market_search_input)
    left_layout.addWidget(self.template_market_category_combo)
    left_layout.addWidget(self.template_market_table, 1)
    market_buttons = QHBoxLayout()
    market_buttons.addWidget(self.template_market_install_button)
    market_buttons.addWidget(self.template_market_apply_button)
    left_layout.addLayout(market_buttons)
    left_layout.addWidget(QLabel("场景模板库"))
    left_layout.addWidget(self.scene_preset_combo)
    left_layout.addWidget(self.apply_scene_preset_button)
    left_layout.addLayout(template_buttons)

    editor_box = QGroupBox("模板编辑")
    editor_layout = QGridLayout(editor_box)
    self.template_name_input = QLineEdit()
    self.template_domain_input = QLineEdit()
    self.template_type_combo = QComboBox()
    for key, text in TEMPLATE_TYPES.items():
        self.template_type_combo.addItem(text, key)
    self.next_page_selector_input = QLineEdit()
    self.next_page_selector_input.setPlaceholderText("可选，例如：a.next, .pagination-next")
    self.template_notes_input = QTextEdit()
    self.template_notes_input.setMaximumHeight(80)

    self.field_table = QTableWidget(0, 4)
    self.field_table.setHorizontalHeaderLabels(["字段名", "CSS 选择器", "取值", "多条"])
    self.field_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
    self.field_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
    self.field_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
    self.field_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
    field_buttons = QHBoxLayout()
    self.add_field_button = QPushButton("添加字段")
    self.remove_field_button = QPushButton("删除字段")
    self.selector_helper_button = QPushButton("点选结果转选择器")
    self.visual_pick_button = QPushButton("打开网页点选字段")
    self.add_field_button.clicked.connect(self.add_field_row)
    self.remove_field_button.clicked.connect(self.remove_selected_field)
    self.selector_helper_button.clicked.connect(self.generate_selector_from_helper)
    self.visual_pick_button.clicked.connect(self.visual_pick_field)
    field_buttons.addWidget(self.add_field_button)
    field_buttons.addWidget(self.remove_field_button)
    field_buttons.addWidget(self.selector_helper_button)
    field_buttons.addWidget(self.visual_pick_button)
    field_buttons.addStretch(1)

    self.pick_url_input = QLineEdit()
    self.pick_url_input.setPlaceholderText("点选网址，留空则使用采集任务里的第一个网址")
    self.pick_field_name_input = QLineEdit()
    self.pick_field_name_input.setPlaceholderText("字段名，例如 标题 / 价格 / 图片")
    self.click_tag_input = QLineEdit()
    self.click_tag_input.setPlaceholderText("点选元素标签，例如 div / h1 / img")
    self.click_id_input = QLineEdit()
    self.click_id_input.setPlaceholderText("元素 id，可空")
    self.click_class_input = QLineEdit()
    self.click_class_input.setPlaceholderText("元素 class，用空格分隔，可空")

    editor_layout.addWidget(QLabel("模板名称"), 0, 0)
    editor_layout.addWidget(self.template_name_input, 0, 1)
    editor_layout.addWidget(QLabel("匹配域名"), 0, 2)
    editor_layout.addWidget(self.template_domain_input, 0, 3)
    editor_layout.addWidget(QLabel("模板类型"), 1, 0)
    editor_layout.addWidget(self.template_type_combo, 1, 1)
    editor_layout.addWidget(QLabel("下一页选择器"), 1, 2)
    editor_layout.addWidget(self.next_page_selector_input, 1, 3)
    editor_layout.addWidget(QLabel("说明"), 2, 0)
    editor_layout.addWidget(self.template_notes_input, 2, 1, 1, 3)
    editor_layout.addWidget(self.field_table, 3, 0, 1, 4)
    editor_layout.addLayout(field_buttons, 4, 0, 1, 4)
    editor_layout.addWidget(QLabel("点选网址"), 5, 0)
    editor_layout.addWidget(self.pick_url_input, 5, 1, 1, 2)
    editor_layout.addWidget(self.pick_field_name_input, 5, 3)
    editor_layout.addWidget(QLabel("点选结果"), 6, 0)
    editor_layout.addWidget(self.click_tag_input, 6, 1)
    editor_layout.addWidget(self.click_id_input, 6, 2)
    editor_layout.addWidget(self.click_class_input, 6, 3)

    splitter.addWidget(left)
    splitter.addWidget(editor_box)
    splitter.setStretchFactor(0, 1)
    splitter.setStretchFactor(1, 3)
    layout.addWidget(splitter)
    return page
